"""Published API contracts; source revisions are recorded in tests/parity-audit.json."""

TASK_PATH = "/qwen-image/tasks"

ENDPOINTS = {
    "qwen_image": {
        "method": "POST",
        "path": "/qwen-image/images",
        "operation": "generate",
        "schema": {
            "type": "object",
            "required": ["model", "prompt"],
            "properties": {
                "model": {"type": "string", "enum": ["qwen-image-3.0", "qwen-image-3.0-pro"]},
                "prompt": {"type": "string", "minLength": 1, "maxLength": 18000},
                "image_urls": {
                    "type": "array",
                    "minItems": 1,
                    "maxItems": 3,
                    "items": {"type": "string", "format": "uri"},
                },
                "n": {"type": "integer", "minimum": 1, "maximum": 6},
                "size": {"type": "string", "pattern": "^[0-9]+\\*[0-9]+$"},
                "prompt_extend": {"type": "boolean"},
                "prompt_extend_mode": {"type": "string", "enum": ["direct", "agent"]},
                "enable_thinking": {"type": "boolean"},
                "negative_prompt": {"type": "string"},
                "seed": {"type": "integer", "minimum": 0, "maximum": 2147483647},
                "watermark": {"type": "boolean"},
                "callback_url": {"type": "string", "format": "uri"},
                "async": {"type": "boolean"},
            },
        },
        "properties": {
            "model": {"type": "string", "enum": ["qwen-image-3.0", "qwen-image-3.0-pro"]},
            "prompt": {"type": "string", "minLength": 1, "maxLength": 18000},
            "image_urls": {
                "type": "array",
                "minItems": 1,
                "maxItems": 3,
                "items": {"type": "string", "format": "uri"},
            },
            "n": {"type": "integer", "minimum": 1, "maximum": 6},
            "size": {"type": "string", "pattern": "^[0-9]+\\*[0-9]+$"},
            "prompt_extend": {"type": "boolean"},
            "prompt_extend_mode": {"type": "string", "enum": ["direct", "agent"]},
            "enable_thinking": {"type": "boolean"},
            "negative_prompt": {"type": "string"},
            "seed": {"type": "integer", "minimum": 0, "maximum": 2147483647},
            "watermark": {"type": "boolean"},
            "callback_url": {"type": "string", "format": "uri"},
            "async": {"type": "boolean"},
        },
        "parameters": [],
        "defaults": {"model": "qwen-image-3.0", "n": 1, "size": "1024*1024"},
        "fixed": {},
        "allow_empty": [],
        "query_actions": [],
        "media_response": True,
    },
    "qwen_image_task_retrieve": {
        "method": "POST",
        "path": "/qwen-image/tasks",
        "operation": "task",
        "schema": {
            "type": "object",
            "properties": {
                "id": {"type": "string"},
                "ids": {"type": "array", "items": {"type": "string"}},
                "action": {"enum": ["retrieve", "retrieve_batch"], "type": "string"},
            },
        },
        "properties": {
            "id": {"type": "string"},
            "ids": {"type": "array", "items": {"type": "string"}},
            "action": {"enum": ["retrieve", "retrieve_batch"], "type": "string"},
        },
        "parameters": [],
        "defaults": {"wait_seconds": 0},
        "fixed": {},
        "allow_empty": [],
        "query_actions": ["retrieve", "retrieve_batch", "list", "presets"],
        "media_response": False,
    },
    "qwen_image_tasks_retrieve_batch": {
        "method": "POST",
        "path": "/qwen-image/tasks",
        "operation": "batch",
        "schema": {
            "type": "object",
            "properties": {
                "id": {"type": "string"},
                "ids": {"type": "array", "items": {"type": "string"}, "minItems": 1},
                "action": {"enum": ["retrieve", "retrieve_batch"], "type": "string"},
            },
            "required": ["action", "ids"],
        },
        "properties": {
            "id": {"type": "string"},
            "ids": {"type": "array", "items": {"type": "string"}, "minItems": 1},
            "action": {"enum": ["retrieve", "retrieve_batch"], "type": "string"},
        },
        "parameters": [],
        "defaults": {},
        "fixed": {"action": "retrieve_batch"},
        "allow_empty": [],
        "query_actions": ["retrieve", "retrieve_batch", "list", "presets"],
        "media_response": False,
    },
}
